module.exports = {
  Lessons: [{
    type: 'category',
    label: 'Cours',
    link: {
      type: 'generated-index',
      title: 'Cours',
      slug: '/Lessons',
    },
    items: [{
      type: 'category',
      label: 'Fondamentaux',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Fondamentaux',
        slug: '/Lessons/Fundamentals',
      },
      items: [{
        type: 'category',
        label: 'Installation',
        link: {
          type: 'doc',
          id: 'Lessons/Fundamentals/Setup/index',
        },
        items: [
          'Lessons/Fundamentals/Setup/Compiler',
          'Lessons/Fundamentals/Setup/IDE',
          'Lessons/Fundamentals/Setup/CMake',
          'Lessons/Fundamentals/Setup/HelloImac',
        ],
      }, 'Lessons/Fundamentals/Introduction',
        'Lessons/Fundamentals/Variables',
        'Lessons/Fundamentals/ConditionsAndLoops',
        'Lessons/Fundamentals/Arrays',
        'Lessons/Fundamentals/Functions',
        'Lessons/Fundamentals/DebuggerAndErrors',
        'Lessons/Fundamentals/Struct',
        'Lessons/Fundamentals/Headers',
        'Lessons/Fundamentals/MemoryAllocation',
        'Lessons/Fundamentals/OOP'],
    }, {
      type: 'category',
      label: 'Algorithmique',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Algorithmique',
        slug: '/Lessons/Algorithmic',
      },
      items: [
        'Lessons/Algorithmic/DataStructures',
        'Lessons/Algorithmic/Operators',
        'Lessons/Algorithmic/Sorting',
        'Lessons/Algorithmic/AutoAndAlgorithm',
        'Lessons/Algorithmic/HashAndAssociativeTables',
        'Lessons/Algorithmic/BinaryTree',
        'Lessons/Algorithmic/Graphs',
        'Lessons/Algorithmic/EncodingAndCompression',
      ],
    }],
  }],
  TDs: [{
    type: 'category',
    label: 'TDs',
    link: {
      type: 'generated-index',
      title: 'TDs',
      slug: '/TDs',
    },
    items: [{
      type: 'category',
      label: 'Fondamentaux',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'TDs Fondamentaux',
        slug: '/TDs/Fundamentals',
      },
      items: [
        'TDs/Fundamentals/Setup',
        'TDs/Fundamentals/Variables',
        'TDs/Fundamentals/ConditionsAndLoops',
        'TDs/Fundamentals/Arrays',
        'TDs/Fundamentals/Functions',
        'TDs/Fundamentals/DebuggerAndErrors',
        'TDs/Fundamentals/Struct',
        'TDs/Fundamentals/Headers',
        'TDs/Fundamentals/MemoryAllocation',
      ],
    }, {
      type: 'category',
      label: 'Algorithmique',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'TDs Algorithmique',
        slug: '/TDs/Algorithmic',
      },
      items: [
        'TDs/Algorithmic/DataStructures',
        'TDs/Algorithmic/Sorting',
        'TDs/Algorithmic/AutoAndAlgorithm',
        'TDs/Algorithmic/HashAndAssociativeTables',
        'TDs/Algorithmic/BinaryTree',
        'TDs/Algorithmic/Graphs',
        'TDs/Algorithmic/EncodingAndCompression',
      ],
    }],
  }],
  Annexes: [{
    type: 'category',
    label: 'Annexes',
    link: {
      type: 'generated-index',
      title: 'Annexes',
      slug: '/Annexes',
    },
    items: [{
      type: "autogenerated",
      dirName: "Annexes"
    }]
  }],
  Workshop: [{
    type: 'category',
    label: 'Workshop',
    link: {
      type: 'generated-index',
      title: 'Workshop',
      slug: '/Workshop',
    },
    items: [{
      type: "autogenerated",
      dirName: "Workshop"
    }]
  }],
  Subjects: [{
    type: 'category',
    label: 'Sujets',
    link: {
      type: 'generated-index',
      title: 'Sujets',
      slug: '/Subjects',
    },
    items: [{
      type: "autogenerated",
      dirName: "Subjects"
    }]
  }],
}
